### ISSUE TITLE
Fatal error: Call to undefined function array_column()

### ISSUE THREAD

**Issue by bbfriend** [mjmjm0101/Coqoo#1]
I get 
Fatal error: Call to undefined function array_column()
 My PHP  < PHP5.5   .sorry

please add 
https://github.com/ramsey/array_column/blob/master/src/array_column.php

**Comment by mjmjm0101** [comment]
Hi, Thank you for your contact .
But it will refuse unfortunately .
Support for PHP 5.4 also by the upstream has expired in September 2015 . 
And this month, the end also of support ver 5.5.

[https://en.wikipedia.org/wiki/PHP#Release_history](https://en.wikipedia.org/wiki/PHP#Release_history)

It does not correspond of 5.4 and for 5.5 in such a state .
Fork to it is recommended that to be added on your own .
